use MVC_SAKSHAM;
CREATE TABLE images(
   id                 INTEGER  NOT NULL PRIMARY KEY 
  ,images0            VARCHAR(47) NOT NULL
  ,images1            VARCHAR(48)
  ,images2            VARCHAR(48)
  ,images3            VARCHAR(56)
  ,images4            VARCHAR(56)
  ,images5            VARCHAR(55)
);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (1,'https://dummyjson.com/image/i/products/1/1.jpg','https://dummyjson.com/image/i/products/1/2.jpg','https://dummyjson.com/image/i/products/1/3.jpg','https://dummyjson.com/image/i/products/1/4.jpg','https://dummyjson.com/image/i/products/1/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (2,'https://dummyjson.com/image/i/products/2/1.jpg','https://dummyjson.com/image/i/products/2/2.jpg','https://dummyjson.com/image/i/products/2/3.jpg','https://dummyjson.com/image/i/products/2/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (3,'https://dummyjson.com/image/i/products/3/1.jpg',NULL,NULL,NULL,NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (4,'https://dummyjson.com/image/i/products/4/1.jpg','https://dummyjson.com/image/i/products/4/2.jpg','https://dummyjson.com/image/i/products/4/3.jpg','https://dummyjson.com/image/i/products/4/4.jpg','https://dummyjson.com/image/i/products/4/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (5,'https://dummyjson.com/image/i/products/5/1.jpg','https://dummyjson.com/image/i/products/5/2.jpg','https://dummyjson.com/image/i/products/5/3.jpg',NULL,NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (6,'https://dummyjson.com/image/i/products/6/1.png','https://dummyjson.com/image/i/products/6/2.jpg','https://dummyjson.com/image/i/products/6/3.png','https://dummyjson.com/image/i/products/6/4.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (7,'https://dummyjson.com/image/i/products/7/1.jpg','https://dummyjson.com/image/i/products/7/2.jpg','https://dummyjson.com/image/i/products/7/3.jpg','https://dummyjson.com/image/i/products/7/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (8,'https://dummyjson.com/image/i/products/8/1.jpg','https://dummyjson.com/image/i/products/8/2.jpg','https://dummyjson.com/image/i/products/8/3.jpg','https://dummyjson.com/image/i/products/8/4.jpg','https://dummyjson.com/image/i/products/8/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (9,'https://dummyjson.com/image/i/products/9/1.jpg','https://dummyjson.com/image/i/products/9/2.png','https://dummyjson.com/image/i/products/9/3.png','https://dummyjson.com/image/i/products/9/4.jpg','https://dummyjson.com/image/i/products/9/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (10,'https://dummyjson.com/image/i/products/10/1.jpg','https://dummyjson.com/image/i/products/10/2.jpg','https://dummyjson.com/image/i/products/10/3.jpg','https://dummyjson.com/image/i/products/10/thumbnail.jpeg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (11,'https://dummyjson.com/image/i/products/11/1.jpg','https://dummyjson.com/image/i/products/11/2.jpg','https://dummyjson.com/image/i/products/11/3.jpg','https://dummyjson.com/image/i/products/11/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (12,'https://dummyjson.com/image/i/products/12/1.jpg','https://dummyjson.com/image/i/products/12/2.jpg','https://dummyjson.com/image/i/products/12/3.png','https://dummyjson.com/image/i/products/12/4.jpg','https://dummyjson.com/image/i/products/12/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (13,'https://dummyjson.com/image/i/products/13/1.jpg','https://dummyjson.com/image/i/products/13/2.png','https://dummyjson.com/image/i/products/13/3.jpg','https://dummyjson.com/image/i/products/13/4.jpg','https://dummyjson.com/image/i/products/13/thumbnail.webp',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (14,'https://dummyjson.com/image/i/products/14/1.jpg','https://dummyjson.com/image/i/products/14/2.jpg','https://dummyjson.com/image/i/products/14/3.jpg','https://dummyjson.com/image/i/products/14/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (15,'https://dummyjson.com/image/i/products/15/1.jpg','https://dummyjson.com/image/i/products/15/2.jpg','https://dummyjson.com/image/i/products/15/3.jpg','https://dummyjson.com/image/i/products/15/4.jpg','https://dummyjson.com/image/i/products/15/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (16,'https://dummyjson.com/image/i/products/16/1.png','https://dummyjson.com/image/i/products/16/2.webp','https://dummyjson.com/image/i/products/16/3.jpg','https://dummyjson.com/image/i/products/16/4.jpg','https://dummyjson.com/image/i/products/16/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (17,'https://dummyjson.com/image/i/products/17/1.jpg','https://dummyjson.com/image/i/products/17/2.jpg','https://dummyjson.com/image/i/products/17/3.jpg','https://dummyjson.com/image/i/products/17/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (18,'https://dummyjson.com/image/i/products/18/1.jpg','https://dummyjson.com/image/i/products/18/2.jpg','https://dummyjson.com/image/i/products/18/3.jpg','https://dummyjson.com/image/i/products/18/4.jpg','https://dummyjson.com/image/i/products/18/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (19,'https://dummyjson.com/image/i/products/19/1.jpg','https://dummyjson.com/image/i/products/19/2.jpg','https://dummyjson.com/image/i/products/19/3.png','https://dummyjson.com/image/i/products/19/thumbnail.jpg',NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (20,'https://dummyjson.com/image/i/products/20/1.jpg','https://dummyjson.com/image/i/products/20/2.jpg','https://dummyjson.com/image/i/products/20/3.jpg','https://dummyjson.com/image/i/products/20/4.jpg','https://dummyjson.com/image/i/products/20/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (21,'https://dummyjson.com/image/i/products/21/1.png','https://dummyjson.com/image/i/products/21/2.jpg','https://dummyjson.com/image/i/products/21/3.jpg',NULL,NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (22,'https://dummyjson.com/image/i/products/22/1.jpg','https://dummyjson.com/image/i/products/22/2.jpg','https://dummyjson.com/image/i/products/22/3.jpg',NULL,NULL,NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (23,'https://dummyjson.com/image/i/products/23/1.jpg','https://dummyjson.com/image/i/products/23/2.jpg','https://dummyjson.com/image/i/products/23/3.jpg','https://dummyjson.com/image/i/products/23/4.jpg','https://dummyjson.com/image/i/products/23/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (24,'https://dummyjson.com/image/i/products/24/1.jpg','https://dummyjson.com/image/i/products/24/2.jpg','https://dummyjson.com/image/i/products/24/3.jpg','https://dummyjson.com/image/i/products/24/4.jpg','https://dummyjson.com/image/i/products/24/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (25,'https://dummyjson.com/image/i/products/25/1.png','https://dummyjson.com/image/i/products/25/2.jpg','https://dummyjson.com/image/i/products/25/3.png','https://dummyjson.com/image/i/products/25/4.jpg','https://dummyjson.com/image/i/products/25/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (26,'https://dummyjson.com/image/i/products/26/1.jpg','https://dummyjson.com/image/i/products/26/2.jpg','https://dummyjson.com/image/i/products/26/3.jpg','https://dummyjson.com/image/i/products/26/4.jpg','https://dummyjson.com/image/i/products/26/5.jpg','https://dummyjson.com/image/i/products/26/thumbnail.jpg');
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (27,'https://dummyjson.com/image/i/products/27/1.jpg','https://dummyjson.com/image/i/products/27/2.jpg','https://dummyjson.com/image/i/products/27/3.jpg','https://dummyjson.com/image/i/products/27/4.jpg','https://dummyjson.com/image/i/products/27/thumbnail.webp',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (28,'https://dummyjson.com/image/i/products/28/1.jpg','https://dummyjson.com/image/i/products/28/2.jpg','https://dummyjson.com/image/i/products/28/3.png','https://dummyjson.com/image/i/products/28/4.jpg','https://dummyjson.com/image/i/products/28/thumbnail.jpg',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (29,'https://dummyjson.com/image/i/products/29/1.jpg','https://dummyjson.com/image/i/products/29/2.jpg','https://dummyjson.com/image/i/products/29/3.webp','https://dummyjson.com/image/i/products/29/4.webp','https://dummyjson.com/image/i/products/29/thumbnail.webp',NULL);
INSERT INTO images(id,images0,images1,images2,images3,images4,images5) VALUES (30,'https://dummyjson.com/image/i/products/30/1.jpg','https://dummyjson.com/image/i/products/30/2.jpg','https://dummyjson.com/image/i/products/30/3.jpg','https://dummyjson.com/image/i/products/30/thumbnail.jpg',NULL,NULL);

select * from images;